package com.citizant.kudos.domain;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "tbl_kudo")
public class Kudo {
	
	private String id;
	private String fromEmail;
	private String toEmail;
	private String kudoCategory;
	private String comment;
	private Date kudoDate;
	private String attachment;
	
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	@DynamoDBAttribute(attributeName = "kudo_from")
	public String getFromEmail() {
		return fromEmail;
	}
	public void setFromEmail(String fromEmail) {
		this.fromEmail = fromEmail;
	}
	@DynamoDBAttribute(attributeName = "kudo_to")
	public String getToEmail() {
		return toEmail;
	}
	public void setToEmail(String toEmail) {
		this.toEmail = toEmail;
	}
	@DynamoDBAttribute(attributeName = "kudo_category")
	public String getKudoCategory() {
		return kudoCategory;
	}
	public void setKudoCategory(String kudoCategory) {
		this.kudoCategory = kudoCategory;
	}
	@DynamoDBAttribute(attributeName = "message")
	public String getComment() {
		return comment;
	}
	public void setComment(String comment) {
		this.comment = comment;
	}
	@DynamoDBAttribute(attributeName = "kudo_date")
	public Date getKudoDate() {
		return kudoDate;
	}
	public void setKudoDate(Date kudoDate) {
		this.kudoDate = kudoDate;
	}
	@DynamoDBAttribute(attributeName = "attachment")
	public String getAttachment() {
		return attachment;
	}
	public void setAttachment(String attachment) {
		this.attachment = attachment;
	}
}
