version: 0.0 
os: linux 
files: 
  - source: kudos.war
    destination: /opt/apache-tomcat-8.0.36/webapps/
hooks: 
   BeforeInstall: 
     - location: scripts/install_dependencies 
       timeout: 300 
   ApplicationStart:
     - location: scripts/start_application 
       timeout: 300 
ApplicationStop: 
     - location: scripts/stop_application
timeout: 300
